name: microEUKscope
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - tiara=1.0.3
  - kaiju
  - krona
  - seqkit
  - eukrep
  - pigz
  - coreutils
  - gawk
  - grep
  - sed
